name: Android CI - SkoolSwap

on:
  push:
    branches:
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Run Tests
        run: ./gradlew test

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SkoolSwap-APK
          path: app/build/outputs/apk/debug/app-debug.apk
